// mod variables;
// mod conditionals;
// mod loops;
// mod functions;
// mod ownership;
// mod references_and_borrowings;
// mod slice;
// mod structs;
// mod methods;
// mod enums;
// mod matchs;
// mod if_let;
// mod vector;
// mod utf8_strings;
// mod hashmap;
// mod panic;
// mod generics;
// mod traits;
// mod lifetimes;
mod practice;

fn main() {
    // println!("Hello, world!");
    // variables::main();
    // conditionals::main();
    // loops::main();
    // functions::main();
    // ownership::main();
    // references_and_borrowings::main();
    // slice::main();
    // structs::main();
    // methods::main();
    // enums::main();
    // matchs::main();
    // if_let::main();
    // vector::main();
    // utf8_strings::main();
    // hashmap::main();
    // panic::main();
    // generics::main();
    // traits::main();
    // lifetimes::main();
    // practice::exercise_1::main();
    // practice::exercise_2::main();
    // practice::exercise_3::main();
    // practice::exercise_4::main();
    practice::exercise_5::main();
}
